#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * Syncthing class.
 *
 * @category   apps
 * @package    syncthing
 * @subpackage scripts
 * @author     eGloo <developer@egloo.ca>
 * @copyright  2017 Avantech
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License version 3 or later
 * @link       http://www.egloo.ca/clearos/marketplace/apps/syncthing
 */

///////////////////////////////////////////////////////////////////////////////
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// N A M E S P A C E
///////////////////////////////////////////////////////////////////////////////

namespace clearos\apps\syncthing;

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// T R A N S L A T I O N S
///////////////////////////////////////////////////////////////////////////////

clearos_load_language('syncthing');

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\syncthing\Syncthing as Syncthing;

clearos_load_library('syncthing/Syncthing');

// Exceptions
//-----------

use \Exception as Exception;

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

// Command line options
//--------------------------------------------------------------------

$short_options = 'f';  // Force

$options = getopt($short_options);

$force = isset($options['f']) ? TRUE : FALSE;

// Command line options
//--------------------------------------------------------------------

$syncthing = new Syncthing();

try {
    $syncthing->restart_multiuser($force);
} catch (Exception $e) {
    echo clearos_exception_message($e) . "\n";
}

if ($force) {
    try {
        $syncthing->update();
    } catch (Exception $e) {
        echo clearos_exception_message($e) . "\n";
    }
}

// vim: syntax=php ts=4
